### ISSUE TITLE
CrXrefSearch can't determine signature

### ISSUE THREAD

**Issue by anforowicz** [chromium/vim-codesearch#4]
Repro:
1. Open src/extensions/renderer/extension_helper.cc
2. Go to line 60, over the ExtensionHostMsg_UpdateDraggableRegions symbol
3. Execute :CrXrefSearch

Expected behavior: Finds xrefs

Actual behavior: Can't determine signature for .../src/extensions/renderer/extension_helper.cc:ExtensionHostMsg_UpdateDraggableRegions

**Comment by asankah** [comment]
Thanks for reporting this. This should be fixed by 081f50bc011359889b447417bd8b9c77bd143395 .

If your local file and the file as known to the CodeSearch backend are out of sync, the library falls back to a fuzzy symbol based search. The matchers used there weren't quite general enough to match IPC message classes.

I updated the library and tested with the file to make sure that the symbol is correctly identified now.
